### ISSUE TITLE
[BUG] 数据库配置项异常

### ISSUE THREAD

**Issue by nfangxu** [DoNewsCode/skeleton#18]
配置文件中设置的数据库配置是 `database`
 
```
# The database configuration
database:
  default:
// ....
```

源码中读取的是 `gorm`  [core/otgorm/dependency.go#L194](https://github.com/DoNewsCode/core/blob/f6c6f14f62b6f50233342fba79f71fbe95caaca0/otgorm/dependency.go#L194)

**Comment by Reasno** [comment]
https://github.com/DoNewsCode/core/pull/51/files

**Comment by nfangxu** [comment]
这里面的配置文件需要改一下

**Comment by nfangxu** [comment]
https://github.com/DoNewsCode/skeleton/blob/master/config/config.yaml#L39

https://github.com/DoNewsCode/skeleton/blob/master/config/config.example.yaml#L39
